repos:
  - repo: local
    hooks:
      - id: export-conda-env
        name: Export Conda Environment
        entry: ./scripts/export_env.sh
        language: script
        always_run: true
        pass_filenames: false
